services:
  fastapi:
    restart: always
    env_file: 
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8001:8080