services:
  fastapi:
    restart: always
    env_file: 
      - .env
    environment:

      DATABASE_URI_LOCAL: ${DATABASE_URI_LOCAL}

      DSN_SENTRY: ${DSN_SENTRY}

    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8001:8080